[book]
title = "mdBook 文档 "
description = "从 markdown 文件创作书籍. 类似 Gitbook 但是由 Rust 实现."
authors = ["Mathieu David", "Michael-F-Bryan"]
translator = "Keunlas"
multilingua = true
language = ["en","zh_CN"]

[rust]
edition = "2018"

[output.html]
mathjax-support = true
site-url = "/tutorial-mdbook/"
git-repository-url = "https://github.com/kirahon/tutorial-mdbook/tree/master/"
edit-url-template = "https://github.com/kirahon/tutorial-mdbook/edit/master/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
